### ISSUE TITLE
 ConceptNet Numberbatch embeddings

### ISSUE THREAD

**Issue by philipposg** [ExplainableML/KG-SP#2]
Hello.
 I tried with to reproduce your scores using this file https://zenodo.org/record/1289942/files/conceptnet-distinguishing-attributes-data.zip as a source for the  ConceptNet Numberbatch embeddings but I got slightly different results .

Would it be possible  to indicate which file you utilized in order to compute the feasability scores?

Thank you.

**Comment by sgk98** [comment]
Hello @philipposg,
Thanks for your interest in our work. The ConceptNet Numberbatch embeddings are available in the following files: `utils/mit_conceptnet.npy`, `utils/zappos_conceptnet.npy`, `utils/cgqa_conceptnet.npy`. 
I hope this helps!
